### ISSUE TITLE
"txm play auditing: Sanity check 0 exceeds maxLength 32665"

### ISSUE THREAD

**Issue by henricook** [hmrc/play-auditing#13]
Hi all,

Just recently i've started seeing these in our frontend app (fset-faststream-frontend) - "[txm play auditing: sanity check 0 exceeds maxLength 32665 - do you need to be auditing this payload?]"

It doesn't seem to make such sense, glancing at AuditFilter it also doesn't seem like it should be possible, since you know the code you might be able to tell me off the top of your heads what you think this might be?

Otherwise i guess i can figure out how to build my own jar of this lib, sub it out in our app and run with slightly different logs so it's clear which line this came from, then trace back to find a fix - let me know!

**Comment by colin-lamed** [comment]
This issue is with `frontend-bootstrap` which has been archived.
