### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by stuartgunter** [hmrc/play-auditing#6]
Please could the license file be updated to include the correct copyright owner information. It looks like this was directly copy & pasted from the template without the required modification.

See: https://github.com/hmrc/play-auditing/blob/f3e078e779ec93cc971cdd09d5203e3e62cf4031/LICENSE#L189

**Comment by beyond-code-github** [comment]
How strange, I'll update this morning. It might be worth checking http-verbs too as this was forked from there so presumably has the same problem if it hasn't been fixed already

**Comment by thorbenlouw** [comment]
PR submitted https://github.com/hmrc/play-auditing/pull/9
